name: Create ISO

on:
  push:
    branches:
      - main
    paths:
      - releng/**

jobs:
  build_iso:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 47005
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"

      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1 --sparse $REPO && cd dune-archiso
          git sparse-checkout set releng
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/cpp-review-dune/introductory-review/aur
          options: --privileged -v ${{github.workspace}}:/home/builder/
          shell: bash
          run: |
            cat /etc/pacman.conf
            sudo chown -R 33333:33333 ~
            echo -e 'Server = http://mirror.math.princeton.edu/pub/archlinux/$repo/os/$arch' | sudo tee /etc/pacman.d/mirrorlist
            cat /etc/pacman.d/mirrorlist
            sudo pacman --needed --noconfirm -Sqyyu git archiso > /dev/null 2>&1
            cd ~
            git clone --filter=blob:none --depth=1 "https://git.omame.xyz/CyberOS/cyberos-keyring.git" && cd cyberos-keyring
            makepkg --noconfirm -si
            sudo mkarchiso -v ~/dune-archiso/releng
            pacman -Qtdq | xargs -r pacman --noconfirm -Rcns > /dev/null 2>&1
            # sudo chmod -R 707 ~/out/*.iso ~/
            rm -rfv /work /home/aur/semicolon_delimited_script
            md5sum /out/*.iso > /out/dunearchiso-`date +%Y.%m.%d`-x86_64.iso.md5
            mv /out/*.{iso,md5} /home/aur/dune-archiso
            ls -la /home/aur/dune-archiso

      - name: "Tar files"
        run: |
          # ls -lR ~/work/dune-archiso/dune-archiso/dune-archiso
          # pwd
          tar --zstd -cf ISO.tar.zst ~/work/dune-archiso/dune-archiso/dune-archiso/*.iso

      - uses: actions/upload-artifact@v2
        with:
          name: ISO-artifact
          path: ISO.tar.zst
          if-no-files-found: error
          retention-days: 90

  # distribute_iso:
  #   runs-on: ubuntu-20.04
  #   needs: build_iso
  #   steps:
  #     - uses: szenius/set-timezone@v1.0
  #       with:
  #         timezoneLinux: "America/Lima"

  #     - name: Download tarball
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ISO-artifact

  #     - name: Untar files
  #       run: |
  #         tar -I zstd -xvf ISO.tar.zst
  #         echo "TODAY=$(echo `date +'%Y.%m.%d'`)" >> $GITHUB_ENV

  #     - name: Create GitHub release
  #       id: create-new-release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v${{ github.run_number }}
  #         release_name: Release ${{ github.run_number }}

  #     - name: Upload asset to GitHub release
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create-new-release.outputs.upload_url }}
  #         asset_path: dunearchiso-${{ env.TODAY }}-x86_64.iso
  #         asset_name: dunearchiso-${{ env.TODAY }}-x86_64.iso
  #         asset_content_type: application/octet-stream
