name: Create ISO

on:
  push:
    branches:
      - main
    # paths:
    #   - releng/**

jobs:
  archiso_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout set releng
          git checkout

      - uses: addnab/docker-run-action@v1
        with:
          image: efikarl/archiso:latest
          options: --privileged -v ${{github.workspace}}:/home/karliso/
          shell: bash
          run: |
            sudo pacman --noconfirm -Sqyu > /dev/null 2>&1
            sudo mkarchiso -v ~/releng
            sudo mv ~/out/*.iso ~/releng
            # ls ~/work ~/out
            # cat ~/releng/packages.x86_64
            # pacman --version
            # sudo --version

      - name: "Tar files"
        run: |
          ls -R
          tar --zstd -cf ISO.tar.zst releng/*.iso

      - uses: actions/upload-artifact@v2
        with:
          name: ISO-artifact
          path: PDF.tar.zst
          if-no-files-found: error
          retention-days: 5
